services:
  ######### [ Reverse proxy ] #########
  reverse-proxy:
    image: nginx:1.26.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/acme/.well-known/acme-challenge:/usr/share/nginx/html/.well-known/acme-challenge:ro
    restart: unless-stopped
    networks:
      - reverse-proxy-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M


  ######### [ Config ] #########
  config-server:
    build:
      context: ./backend/config
    environment:
      - SPRING_PROFILES_ACTIVE=native,prod
    env_file:
      - .env
    volumes:
      - ./backend/config/src/main/resources/configurations:/app/configurations
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:7777/actuator/health || exit 1" ]
      interval: 5s
      timeout: 5s
      retries: 25
      start_period: 5s
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  ######### [ Gateway ] #########
  gateway-server:
    build:
      context: ./backend/gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:9999/actuator/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 8s
    networks:
      - reverse-proxy-net
      - gateway-net
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1536M


  ######### [ Data & Finance ] #########
  data-server:
    build:
      context: ./backend/data
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      mongodb-finance:
        condition: service_healthy
      selenium-chrome:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
      - database-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1536M

  finance-server:
    build:
      context: ./backend/finance
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      mongodb-finance:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
      - database-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1536M

  mongodb-finance:
    image: mongo:8.0
    container_name: mongodb-finance
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_FINANCE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_FINANCE_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_FINANCE_DB}
    volumes:
      - mongodb_finance_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: [
        "CMD", "mongosh",
        "-u", "${MONGO_FINANCE_USER}",
        "-p", "${MONGO_FINANCE_PASSWORD}",
        "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  ######### [ Wallet ] #########
  wallet-server:
    build:
      context: ./backend/wallet
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      postgres-wallet:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
      - database-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1024M

  postgres-wallet:
    image: postgres:17.4
    container_name: postgres-wallet
    environment:
      POSTGRES_USER: ${POSTGRES_WALLET_USER}
      POSTGRES_PASSWORD: ${POSTGRES_WALLET_PASSWORD}
      POSTGRES_DB: ${POSTGRES_WALLET_DB}
    volumes:
      - postgres_wallet:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_WALLET_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  ######### [ Subscription ] #########
  subscription-server:
    build:
      context: ./backend/subscription
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      config-server:
        condition: service_healthy
      mongodb-subscription:
        condition: service_healthy
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
      - database-net
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1536M

  mongodb-subscription:
    image: mongo:8.0
    container_name: mongodb-subscription
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_SUBSCRIPTION_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_SUBSCRIPTION_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_SUBSCRIPTION_DB}
    volumes:
      - mongodb_subscription_data:/data/db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 768M


  ######### [ Notification ] #########
  notification-server:
    build:
      context: ./backend/notification
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
    depends_on:
      kafka-1:
        condition: service_healthy
      kafka-2:
        condition: service_healthy
      config-server:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  ######### [ Authentication ] #########
  keycloak:
    image: quay.io/keycloak/keycloak:26.1
    container_name: keycloak
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
      KC_DB_SCHEMA: public
      KC_DB_INIT_SCHEMA: "true"

      KC_HTTP_ENABLED: "true"
      KC_HTTPS_ENABLED: "false"
      KC_HOSTNAME: auth.muybien.pl

      KC_HOSTNAME_V2: "true"
      KC_HOSTNAME_V2_PROXY: edge
      KC_HOSTNAME_V2_STRICT: "true"
      KC_HOSTNAME_V2_STRICT_HTTPS: "true"
      KC_HOSTNAME_V2_ADMIN: https://auth.muybien.pl

      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_BOOTSTRAP_ADMIN_USER: ${KC_ADMIN_USER}
      KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}

    #      KC_HEALTH_ENABLED: "true"
    #      KC_METRICS_ENABLED: "true"
    command:
      - start
      - --import-realm
    volumes:
      - keycloak_data:/opt/keycloak/data
      - keycloak_data:/opt/keycloak/themes
      - ./init/marketsync-client-prod.json:/opt/keycloak/data/import/marketsync-client-prod.json
    depends_on:
      postgres-keycloak:
        condition: service_healthy
    networks:
      - reverse-proxy-net
      - database-net
    #    healthcheck:
    #      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/9000;echo -e 'GET /health/ready HTTP/1.1\r\nhost: http://localhost\r\nConnection: close\r\n\r\n' >&3;if [ $? -eq 0 ]; then echo 'Healthcheck Successful';exit 0;else echo 'Healthcheck Failed';exit 1;fi;"]
    #      interval: 5s
    #      timeout: 5s
    #      retries: 30
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M

  postgres-keycloak:
    image: postgres:17.4
    container_name: postgres-keycloak
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: ${POSTGRES_KEYCLOAK_PASSWORD}
    volumes:
      - postgres_keycloak:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U keycloak" ]
      interval: 5s
      timeout: 5s
      retries: 15
    networks:
      - database-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M


  ######### [ Selenium ] #########
  selenium-chrome:
    image: selenium/standalone-chromium:4.28.1
    container_name: selenium-chrome
    shm_size: 2g
    ports:
      - "4444:4444"
    environment:
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
    healthcheck:
      test: [ "CMD-SHELL", "curl -fs http://localhost:4444/status | grep -q '\"ready\": true'" ]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 3072M



  ######### [ Zookeeper ] #########
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper-1
    restart: unless-stopped
    volumes:
      - zookeeper_data_1:/var/lib/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper-2
    restart: unless-stopped
    volumes:
      - zookeeper_data_2:/var/lib/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.9.0
    container_name: zookeeper-3
    restart: unless-stopped
    volumes:
      - zookeeper_data_3:/var/lib/zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_SERVERS: zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "2181" ]
      start_period: 10s
      interval: 5s
      timeout: 5s
      retries: 10

  ######### [ Kafka Brokers ] #########
  kafka-1:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka-1
    restart: unless-stopped
    volumes:
      - kafka_data_1:/var/lib/kafka
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092" ]
      start_period: 40s
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-2:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka-2
    restart: unless-stopped
    volumes:
      - kafka_data_2:/var/lib/kafka
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9094" ]
      start_period: 40s
      interval: 10s
      timeout: 10s
      retries: 10

  kafka-3:
    image: confluentinc/cp-kafka:7.9.0
    container_name: kafka-3
    restart: unless-stopped
    volumes:
      - kafka_data_3:/var/lib/kafka
    depends_on:
      zookeeper-1:
        condition: service_healthy
      zookeeper-2:
        condition: service_healthy
      zookeeper-3:
        condition: service_healthy
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9096
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-3:9096
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    healthcheck:
      test: [ "CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9096" ]
      start_period: 40s
      interval: 10s
      timeout: 10s
      retries: 10

  ######### [ Frontend ] #########
  frontend-server:
    build:
      context: ./frontend
      args:
        - ENV_CONFIGURATION=production
    restart: unless-stopped
    networks:
      - reverse-proxy-net
      - gateway-net
    deploy:
      resources:
        limits:
          cpus: '1.5'
          memory: 2048M


networks:
  reverse-proxy-net:
    driver: bridge
  gateway-net:
    driver: bridge
  backend-net:
    driver: bridge
  database-net:
    driver: bridge

volumes:
  keycloak_data:
  postgres_keycloak:
  postgres_wallet:
  mongodb_finance_data:
  mongodb_subscription_data:
  zookeeper_data_1:
  zookeeper_data_2:
  zookeeper_data_3:
  kafka_data_1:
  kafka_data_2:
  kafka_data_3:
