server:
  port: 9999

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: finance-service
              uri: http://localhost:8800
              predicates:
                - Path=/api/v1/finances/**
            - id: subscription-service
              uri: http://localhost:8900
              predicates:
                - Path=/api/v1/subscriptions/**
            - id: wallet-service
              uri: http://localhost:8200
              predicates:
                - Path=/api/v1/wallets/**
            - id: wallet-ws
              uri: http://localhost:8200
              predicates:
                - Path=/api/ws-wallet/**

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/marketsync-client


frontend-url: http://localhost:4200

jwk-uri: http://localhost:8080/realms/marketsync-client/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always