server:
  port: 9000

kafka:
  enabled: true

spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    consumer:
      group-id: send-notification-event
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: >
          subscriptionConfirmation:pl.muybien.kafka.confirmation.SubscriptionConfirmation,
          supportConfirmation:pl.muybien.kafka.confirmation.SupportConfirmation
      isolation-level: read_committed

  cloud:
    aws:
      region:
        static: us-east-1
        auto: false
      stack:
        auto: false
      credentials:
        access-key: -----
        secret-key: -----

support:
  notification:
    technics:
      emails:
        - "your@email.com"
      numbers:
        - ""
    supports:
      emails:
        - "your@email.com"
      numbers:
        - ""

