server:
  port: 8200

spring:
  datasource:
    username: wallet
    password: wallet
    url: jdbc:postgresql://localhost/wallet?sslmode=disable
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092,localhost:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

application:
  config:
    finance-url: http://localhost:8800/api/v1/finances

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

wallet:
  websocket:
    refresh-interval-ms: 5000 # 5 second interval

frontend-url: http://localhost:4200
