server:
  port: 9999

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          routes:
            - id: finance-service
              uri: http://finance-server:8800
              predicates:
                - Path=/v1/finances/**
            - id: subscription-service
              uri: http://subscription-server:8900
              predicates:
                - Path=/v1/subscriptions/**
            - id: wallet-service
              uri: http://wallet-server:8200
              predicates:
                - Path=/v1/wallets/**
            - id: wallet-ws
              uri: http://wallet-server:8200
              predicates:
                - Path=/ws-wallet/**

  security:
    oauth2:
      resourceserver:
        issuer-uri: ${KEYCLOAK_ISSUER_URL}

frontend-url: ${FRONTEND_URL}

jwk-uri: ${JWK_URI}

management:
  endpoints:
    web:
      exposure:
        include: health,info