server:
  port: 8900

schedule:
  time-ms: 30000 # 30s
  fetch-page-size-per-round: 10

kafka:
  enabled: true

spring:
  mongodb:
    host: mongodb-subscription
    port: 27017
    username: ${MONGO_SUBSCRIPTION_USER}
    password: ${MONGO_SUBSCRIPTION_PASSWORD}
    authentication-database: admin
  kafka:
    bootstrap-servers: ${BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
application:
  config:
    finance-url: ${FINANCE_API_URL}

send-notification-topic: send-notification-topic